service: frankandoak-netsuite-asn-import

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
custom:
  pythonRequirements:
    dockerizePip: false

package:
  exclude:
    - ./**
  include:
    - netsuite_asn_import/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  tenant: frankandoak
  region: us-east-1
  deploymentBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  configBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz
  role: arn:aws:iam::#{AWS::AccountId}:role/LambdaExecutionRole
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:provider.tenant}
    SEARCH_PAGE_SIZE: 50

functions:
  asn_import:
    name: ${self:provider.tenant}-asn-netsuite-to-newstore
    handler: netsuite_asn_import.aws.import_netsuite_item_fulfillments.handler
    timeout: 900
    memorySize: 256
    events:
      - schedule:
          name: ${self:provider.tenant}-asn-netsuite-to-newstore-trigger
          rate: rate(2 hours)
