service: ${self:custom.tenant}-netsuite-availability-import
frameworkVersion: ^2.34.0
configValidationMode: error

plugins:
  - serverless-python-requirements
  - serverless-plugin-existing-s3
custom:
  tenant: frankandoak
  configBucket: ${self:custom.tenant}-${self:provider.stage}-0-newstore-dmz
  pythonRequirements:
    dockerizePip: false

package:
  patterns:
    - '!./**'
    - netsuite_availability_import/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  region: us-east-1
  deploymentBucket: ${self:custom.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"

functions:
  availability_import_csv_to_import:
    name: ${self:custom.tenant}-cii-inventory-csv-to-import
    handler: netsuite_availability_import.aws.lambda_csv_to_import.handler
    timeout: 300
    memorySize: 256
    environment:
      REGION: ${self:provider.region}
      CFR_TABLE: ${self:resources.Resources.CFRTable.Properties.TableName}
      S3_BUCKET_NAME: ${self:custom.configBucket}
      S3_CHUNK_INTERVAL: "30"
      S3_CHUNK_SIZE: "1000"
      S3_PREFIX: queued_for_import/
      STATE_MACHINE_ARN: !Sub "arn:aws:states:us-east-1:${AWS::AccountId}:stateMachine:stn-state-machine"
      TENANT: ${self:custom.tenant}
      STAGE: ${self:provider.stage}
      LOG_LEVEL: INFO
      PHYSICAL_GC_ID: PGC
      PHYSICAL_GC_SKU: 5500000-000
      newstore_url_api: ${self:custom.tenant}.${self:provider.stage}.newstore.net
      newstore_use_auth_lambda: 1
      newstore_auth_lambda: ${self:custom.tenant}-auth-token-generator-${self:provider.stage}-get_auth_token
    events:
      - s3:
          bucket: ${self:custom.configBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: import_CSVs/FAONSINV_
            - suffix: .csv
          existing: true
resources:
  Resources:
    CFRTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: cfr_table
        BillingMode: PAY_PER_REQUEST
