service: frankandoak-csv-price-processor

plugins:
  - serverless-python-requirements
package:
  exclude:
    - ./**
  include:
    - csv_price_processor/**

custom:
  tenant: ${opt:tenant, 'frankandoak'}
  stage: ${opt:stage, 'x'}
  pythonRequirements:
    dockerizePip: false

provider:
  name: aws
  runtime: python3.7
  stage: ${self:custom.stage}
  tenant: ${self:custom.tenant}
  region: us-east-1
  deploymentBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole'
  environment:
    S3_BUCKET: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz

functions:
  CsvPriceProcessor:
    name: ${self:provider.tenant}-csv-price-processor
    handler: csv_price_processor.aws.csv_price_processor.handler
    timeout: 15
    memorySize: 128
    environment:
      S3_BUCKET: ${self:provider.environment.S3_BUCKET}
      S3_PREFIX: 'import_files/'
      CHUNK_SIZE: '10000'
      SECS_BETWEEN_CHUNKS: '300'
      STATE_MACHINE_ARN: !Sub 'arn:aws:states:us-east-1:${AWS::AccountId}:stateMachine:stn-state-machine'
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: import_CSVs/MLNSPRC
            - suffix: .csv
          existing: true
