service: frankandoak-shopify-process-return

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: false

package:
  exclude:
    - ./**
  include:
    - shopify_process_return/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  tenant: frankandoak
  region: us-east-1
  deploymentBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  configBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz
  role: arn:aws:iam::#{AWS::AccountId}:role/LambdaExecutionRole
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:provider.tenant}
    REGION: ${self:provider.region}
    warehouse_usc: MTLDC1
    newstore_auth_lambda: ${self:provider.tenant}-auth-token-generator-${self:provider.stage}-get_auth_token
    newstore_url_api: ${self:provider.tenant}.${self:provider.stage}.newstore.net
    newstore_use_auth_lambda: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:GetQueueAttributes
      Resource: !GetAtt ShopifyReturnQueue.Arn

functions:
  receive_shopify_return:
    name: ${self:provider.tenant}-receive-shopify-return
    handler: shopify_process_return.receive_refund.handler
    timeout: 300
    memorySize: 128
    environment:
      sqs_returns_name: ${self:provider.tenant}-refunds-processor
    events:
      - http: POST /d/shopify/process/return

  process_shopify_return:
    name: ${self:provider.tenant}-process-shopify-return
    handler: shopify_process_return.process_refund.handler
    timeout: 120
    memorySize: 128
    environment:
      warehouse_usc: USC
      sqs_returns_name:
        Fn::GetAtt:
          - ShopifyReturnQueue
          - QueueName
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ShopifyReturnQueue
              - Arn
          batchSize: 1

  register_hook_on_newstore:
    name: ${self:provider.tenant}-shopify-register-return-hook
    handler: shopify_process_return.register_hook.handler
    timeout: 300
    memorySize: 128
    environment:
      PROCESS_RETURN_URL: ''
    events:
      - schedule:
          name: ${self:provider.tenant}-shopify-trigger-register-return-hook
          rate: rate(1 day)

  sync_returns_from_shopify:
    name: ${self:provider.tenant}-shopify-sync-returns-with-shopify
    handler: shopify_process_return.sync_refund.handler
    timeout: 300
    memorySize: 128
    environment:
      sqs_returns_name:
        Fn::GetAtt:
          - ShopifyReturnQueue
          - QueueName
    events:
      - schedule:
          name: ${self:provider.tenant}-shopify-trigger-sync-returns-with-shopify
          rate: rate(1 day)

resources:
  Resources:
    ShopifyReturnQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.tenant}-refunds-processor
        VisibilityTimeout: 300
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt ShopifyReturnDeadLetterQueue.Arn
          maxReceiveCount: 24

    ShopifyReturnDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.tenant}-refunds-processor-dlq
