service: ${self:custom.tenant}-sailthru-integration
frameworkVersion: ^2.34.0
configValidationMode: error

plugins:
  - serverless-python-requirements

custom:
  tenant: frankandoak
  configBucket: ${self:custom.tenant}-${self:provider.stage}-0-newstore-dmz

  pythonRequirements:
    dockerizePip: false

package:
  patterns:
    - sailthru_integration/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket: ${self:custom.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole'
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:custom.tenant}

functions:
  sailthru:
    name: ${self:custom.tenant}-sailthru
    handler: sailthru_integration.invoke_sailthru.handler
    timeout: 30
    memorySize: 128
    environment:
      SAILTHRU_CREDS_PARAM: sailthru_credentials
    events:
      - http: POST /invoke
