service: frankandoak-order-id-to-fulfillment-request
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: false

package:
  exclude:
    - ./**
  include:
    - order_id_to_fulfillment_request/**

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'x'}
  tenant: frankandoak
  region: us-east-1
  deploymentBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz-deploy
  configBucket: ${self:provider.tenant}-${self:provider.stage}-0-newstore-dmz
  iam.role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaExecutionRole"
  environment:
    STAGE: ${self:provider.stage}
    TENANT: ${self:provider.tenant}
    REGION: ${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:GetQueueAttributes
      Resource: !GetAtt YotpoOrderOpenQueue.Arn

functions:
  yotpo_webhook:
    name: ${self:provider.tenant}-yotpo-webhook
    handler: yotpo_shopper_loyalty.aws.yotpo_event_listener.handler
    timeout: 300
    memorySize: 128
    events:
      - http: POST /yotpo_event_stream
